### PR TITLE
Add support for date type

### LINKED ISSUE #128: Error: Don't know how to convert type date
Querying a simple table containing a date types column with SELECT \* ... LIMIT 10 I get the error

```
library(bigrquery)
project <- "***" # put your project ID here
sql <- "select date_dt from test.table limit 10"
df <- query_exec(sql, project = project)

Error: Don't know how to convert type date
```

Selecting a subset of columns without the date column succeeds, and selecting only the date column generates the error.

### PR DESCRIPTION
**Pull request by kmatt**
Resolves #128

### CODE REVIEW

**Comment by craigcitro** [comment]
So this seems totally reasonable to me -- @hadley, are there gotchas we should know about using `as.Date`?

**Comment by hadley** [comment]
I don't remember how this code works, but the patch is unlikely to work given that `as.Date(1)` fails.

**Comment by kmatt** [comment]
What's the proper approach, as this should be dealing with data enforced as proper dates from the database?

**Comment by jarodmeng** [comment]
`Date` type is only recently added to Big Query in beta release of the standard sql (see [documentation](https://cloud.google.com/bigquery/sql-reference/data-types#date-type)). For a BQ table field to have the type `Date`, it follows the `'YYYY-[M]M-[D]D'` format which should be compatible with `as.Date()` in R. Since `converter()` will only be called on `Date` type field values, I don't see how it would run into calls like `as.Date(1)`.

**Comment by craigcitro** [comment]
@hadley I think it's as safe as any of the other format conversions -- they all assume that the data coming in on the wire will be of the described format, which I think is safe?

Of course, a better first step would be to actually write some tests for `extract_data`, which can happen independent of getting any auth bits in place. 😉

**Comment by page1** [comment]
This solved my ```Error: Don't know how to convert type date```

**Comment by kmatt** [comment]
@hadley @jarodmeng And from that BigQuery doc page "Represents a logical calendar date. Values range between the years 1 and 9999, inclusive", this as.Date() should only receive valid date strings.  The code should not receive the infamous "0000-00-00" MySQL-valid date.

**Comment by blakeyc** [comment]
Just checking if there is any updates/movement on this one, would be great to not have to remember to convert to timestamps where ever a date is used in queries.

**Comment by inkrement** [comment]
Please add support for all the other Data Types (e.g., DateTime, Date and Time) too.

**Comment by hadley** [comment]
Could someone please provide a minimal reprex that illustrates when this currently fails?

**Pull request closed without merging**
