### PR TITLE
Feat: list_tables() returns more than 1000 results

### PR DESCRIPTION
**Pull request by fieldryand**
Hi! This PR enables pagination through the results of the tables.list endpoint, allowing more than the default 1000 table names to be returned. This feature was requested in #58.

I see that `list_tabledata()` uses a callback to append the paginated results. I would be open to using the same approach here if you think it's beneficial.

Cheers!

### CODE REVIEW

**Comment by krlmlr** [comment]
I've noticed that max_results = NULL currently implies that 50 results are returned. Would you mind taking a look at this in the scope of this PR?

**Comment by fieldryand** [comment]
Thanks for pointing that out--I will take a look.

**Comment by hadley** [comment]
@fieldryand are you still interested in this PR?

**Comment by hadley** [comment]
Actually I think it's better to do this at the request level so it's a bit more generalised

**Pull request closed without merging**
