### PR TITLE
read_big_query() added

### PR DESCRIPTION
**Pull request by Mullefa**
I have found this function to be very convenient when working with either large queries, or lots of queries, or queries that can be parametrised by some variable(s).

### CODE REVIEW

**Comment by krlmlr** [comment]
I'm not sure this belongs in bigrquery.

**Comment by Mullefa** [comment]
Agreed. I was going to suggest the [SQL](https://github.com/rstats-db/SQL) package, but saw it has been deprecated. Doesn't seem like DBI is the place to put it either though?!

**Comment by krlmlr** [comment]
In the future, DBI might offer support for parametrized queries (rstats-db/DBI#63), even if the backend doesn't support it. I remember that similar functionality is available in the ProjectTemplate package, too.

**Comment by hadley** [comment]
Yeah, this doesn't belong in bigrquery, sorry.

**Pull request closed without merging**
